hostname attacker
!
interface lo
 ip address 192.0.2.1/24
 ip address 203.0.113.1/25
!
interface eth1
 ip address 10.0.3.2/30
!
router bgp 65666
 bgp router-id 10.255.0.66
 no bgp ebgp-requires-policy
 neighbor 10.0.3.1 remote-as 65001
 neighbor 10.0.3.1 description transit
 !
 address-family ipv4 unicast
  network 192.0.2.0/24
  neighbor 10.0.3.1 activate
 exit-address-family
!
