hostname victim
!
interface lo
 ip address 203.0.113.1/24
!
interface eth1
 ip address 10.0.1.1/30
!
router bgp 65010
 bgp router-id 10.255.0.10
 no bgp ebgp-requires-policy
 neighbor 10.0.1.2 remote-as 65001
 neighbor 10.0.1.2 description transit
 !
 address-family ipv4 unicast
  network 203.0.113.0/24
  neighbor 10.0.1.2 activate
 exit-address-family
!
