hostname transit
!
interface eth1
 ip address 10.0.1.2/30
!
interface eth2
 ip address 10.0.2.1/30
!
interface eth3
 ip address 10.0.3.1/30
!
rpki
 rpki cache tcp 172.20.20.6 3323 preference 1
exit
!
bgp community-list standard CL-RPKI-INVALID permit no-export
!
route-map RM-RPKI-IN deny 10
 match rpki invalid
!
route-map RM-RPKI-IN permit 20
!
router bgp 65001
 bgp router-id 10.255.0.1
 no bgp ebgp-requires-policy
 neighbor 10.0.1.1 remote-as 65010
 neighbor 10.0.1.1 description victim
 neighbor 10.0.2.2 remote-as 65020
 neighbor 10.0.2.2 description user
 neighbor 10.0.3.2 remote-as 65666
 neighbor 10.0.3.2 description attacker
 !
 address-family ipv4 unicast
  neighbor 10.0.1.1 activate
  neighbor 10.0.2.2 activate
  neighbor 10.0.3.2 activate
  neighbor 10.0.3.2 route-map RM-RPKI-IN in
 exit-address-family
!
