hostname transit
!
interface eth1
 ip address 10.0.1.2/30
!
interface eth2
 ip address 10.0.2.1/30
!
interface eth3
 ip address 10.0.3.1/30
!
rpki
 rpki cache tcp 172.20.20.200 3323 preference 1
exit
!
route-map RM-RPKI-IN deny 10
 match rpki invalid
!
route-map RM-RPKI-IN permit 20
!
router bgp 65001
 bgp router-id 10.255.0.1
 no bgp ebgp-requires-policy
 neighbor 10.0.1.1 remote-as 65010
 neighbor 10.0.1.1 description victim
 neighbor 10.0.2.2 remote-as 65020
 neighbor 10.0.2.2 description user
 neighbor 10.0.3.2 remote-as 65666
 neighbor 10.0.3.2 description attacker
 !
 address-family ipv4 unicast
  neighbor 10.0.1.1 activate
  neighbor 10.0.2.2 activate
  neighbor 10.0.3.2 activate
  neighbor 10.0.3.2 soft-reconfiguration inbound
  neighbor 10.0.3.2 route-map RM-RPKI-IN in
 exit-address-family
 !
 bmp targets COLLECTOR
  bmp connect 172.20.20.201 port 5000 min-retry 1000 max-retry 10000
  bmp monitor ipv4 unicast pre-policy
  bmp monitor ipv4 unicast post-policy
  bmp monitor ipv4 unicast loc-rib
 exit
!
